### PR TITLE
2.3.1 Develop to Release

### PR DESCRIPTION
**Pull request by MechaRyRy**
We want to release the following:

#488 Downloaded notification re-shown
#479 Quick Returns 

Version 2.3.1 because this is patching a bug and not much else.

### CODE REVIEW

**Comment by MechaRyRy** [comment]
There's an excessive number of commits because of a squash that was previously used. In case you are wondering.

**Comment by zegnus** [comment]
@Mecharyry a squash collapses several commits into one, how come there is an excessive number of commits because of a previous squash?

**Comment by MechaRyRy** [comment]
@zegnus I don't honestly know but it's the only thing that has changed between the past release and all others as far as I can tell. The changes are correct but the reported commits are just all present.

**Comment by Dorvaryn** [comment]
If those previous changes were squashed into release before and release was not merged back into develop subsequently then those commits still exist into develop, hence why this PR shows them all. We can merge as is or we could try and merge release into develop first to see if this workflow would prevent such issues in the future.

**Comment by zegnus** [comment]
Ah yes, I was thinking that same scenario

**Comment by MechaRyRy** [comment]
I've tried merging release into develop thinking that might solve the issue, it did not 😄

**Review by Dorvaryn — APPROVED** [review]

**Comment by Dorvaryn** [comment]
No point blocking this since the diff is correct. But we might need to define a proper workflow if we want to use squashes. Prs like this will make following what is going on a lot more complicated

**Review by zegnus — APPROVED** [review]

**Pull request merged**
