### PR TITLE
Allow downloading to location returned from getExternalFilesDirs

### PR DESCRIPTION
**Pull request by Hackmodford**
I believe I have fixed the build error from my previous submission #203 and fixes issue #201 . I also tried to adjust the formatting to fit the official style. (sorry, I'm manually editing this in Github)

If there are any other issues, I'll do my best to fix them.

### CODE REVIEW

**Comment by stefanhoth** [comment]
Can one of the admins review this PR?

**Comment by xrigau** [comment]
ok to test

**Comment by xrigau** [comment]
Awesome @Hackmodford ! No comments means :shipit:

**Comment by xrigau** [comment]
Version `0.2.44` released 🎉 ! https://bintray.com/novoda/maven/download-manager/0.2.44

**Pull request merged**
