### PR TITLE
Give the paused state a higher priority

### PR DESCRIPTION
**Pull request by amlcurran**
Allows a batch which is half way through being paused to be considered paused, rather than flicking between running and paused as it currently does.

This also updates appcompat because of Lint errors

### CODE REVIEW

**Comment by hal9002** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.novoda.com/job/download-manager-prb/156/
Test FAILed.

**Comment by hal9002** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.novoda.com/job/download-manager-prb/157/
Test PASSed.

**Comment by xrigau** [comment]
:+1: seems legit

**Comment by ouchadam** [comment]
:+1:  will be the same change for paused by wifi @zegnus

**Pull request merged**
