### PR TITLE
Check whether a wakeLock is held before releasing

### PR DESCRIPTION
**Pull request by MechaRyRy**
## Problem
We aren't checking whether we hold a wake lock before attempting to release it, this can lead to a crash 😬 

## Solution
Check whether we hold a given wake lock before attempting to release it.

### CODE REVIEW

**Comment by MechaRyRy** [comment]
Wondering if we should also attempt to catch the exception?

**Review by danybony — APPROVED** [review]
I wouldn't try to catch the exception.
With this check we should be safe from un-held wakelocks, if something else it's happening it's not something we can control/recover

**Review by rock3r — APPROVED** [review]
I'm against swallowing the exception too; I am ok with the fix but I am wondering how on earth would we not have the wakelock at that point? Would it be because of App Standby or Doze not granting us wakelocks?

**Comment by MechaRyRy** [comment]
We've seen this on Samsung devices :trollface: it seems to be from bugs in other libraries 😬 

https://stackoverflow.com/questions/12140844/java-lang-runtimeexception-wakelock-under-locked-c2dm-lib

https://github.com/evernote/android-job/issues/29

We've added it here to try and guard against this happening.

**Comment by rock3r** [comment]
Oh nice 🙄 Well let's ship!

**Pull request merged**
