### PR TITLE
Create service connection listener after liteDownloadManager

### LINKED ISSUE #510: Attempt to invoke virtual method 'void Ep.submitAllStoredDownloads(com.novoda.downloadmanager.AllStoredDownloadsSubmittedCallback)' on a null object reference
Im seeing this crash in production, but am not able to reproduce it.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void Ep.submitAllStoredDownloads(com.novoda.downloadmanager.AllStoredDownloadsSubmittedCallback)' on a null object reference
       at com.novoda.downloadmanager.DownloadManagerBuilder$1.onServiceConnected + 252(DownloadManagerBuilder.java:252)
       at android.app.LoadedApk$ServiceDispatcher.doConnected + 1335(LoadedApk.java:1335)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run + 1352(LoadedApk.java:1352)
       at android.os.Handler.handleCallback + 739(Handler.java:739)
       at android.os.Handler.dispatchMessage + 95(Handler.java:95)
       at android.os.Looper.loop + 158(Looper.java:158)
       at android.app.ActivityThread.main + 7224(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 1230(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main + 1120(ZygoteInit.java:1120)
```

It does not seem to be specific to OS version, or device manufacturer, and it is happening with the app in the foreground and background.

Using version 2.3.0.

### PR DESCRIPTION
**Pull request by JesseCrocker**
In my application `onServiceConnected` seems to sometimes get called immediately after `applicationContext.bindService(...)` is called, which causes a crash, because `liteDownloadManager` is not initialized yet. This PR calls bindService after liteDownloadManager is initialized to eliminate the possibility of this crash.

Fixes #510

### CODE REVIEW

**Comment by hal9002** [comment]
Can one of the admins review this PR?

**Comment by Mecharyry** [comment]
test please

**Review by zegnus — APPROVED** [review]
Good one 👍

**Comment by zegnus** [comment]
test this please

**Comment by zegnus** [comment]
@JesseCrocker you need to update this dependency, otherwise, the build will fail:
- A newer version of com.google.truth:truth than 0.44 is available: 1.0

ping me when done

**Pull request closed without merging**
