### PR TITLE
Replace ListView with RecyclerView in demos

### PR DESCRIPTION
**Pull request by ronocod**
The lists in the demos were using `ListView` without the ViewHolder pattern. This caused higher CPU usage than necessary when updating the lists as all the Views were being recreated on each update.

Rather than just implementing the ViewHolder pattern on the ListView adapters I decided to move all the lists to RecyclerView.

UI is the same as before.

### CODE REVIEW

**Comment by hal9002** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.novoda.com/job/download-manager-prb/200/
Test PASSed.

**Comment by rock3r** [comment]
I think this is YAGNI unless you actually need a `RecyclerView`... :dancer:

**Comment by xrigau** [comment]
yagni - but since it's already done :+1:

**Comment by xrigau** [comment]
:shipit:

**Comment by hal9002** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.novoda.com/job/download-manager-prb/202/
Test FAILed.

**Comment by xrigau** [comment]
can't handle the hype

**Pull request merged**
