### PR TITLE
Rename DownloadThread to DownloadTask

### PR DESCRIPTION
**Pull request by amlcurran**
The download thread object isn't actually a thread, its a Runnable which is submitted to an Executor. I renamed it so that it is more explicit about its role!

### CODE REVIEW

**Comment by ronocod** [comment]
:+1:

**Comment by hal9002** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.novoda.com/job/download-manager-prb/199/
Test PASSed.

**Comment by danybony** [comment]
:100:

**Comment by blundell** [comment]
:+1:

**Pull request merged**
