### PR TITLE
Testing PRB

### PR DESCRIPTION
**Pull request by amlcurran**

### CODE REVIEW

**Comment by amlcurran** [comment]
test this

**Comment by blundell** [comment]
I added the webhook to the settings

**Comment by hal9002** [comment]
Can one of the admins review this PR?

**Comment by blundell** [comment]
test this please

**Comment by amlcurran** [comment]
I did that and didn't press save D:

**Comment by amlcurran** [comment]
test this

**Comment by blundell** [comment]
i've never seen the chat hook work, i just close n reopen or push more :)

**Comment by amlcurran** [comment]
\o/

**Comment by blundell** [comment]
ヽ(◉◡◔)ﾉ

**Comment by hal9002** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://ci.novoda.com/job/download-manager-prb/1/
Test PASSed.

**Comment by xrigau** [comment]
(☞ﾟヮﾟ)☞

**Comment by xrigau** [comment]
I guess can be closed then :+1:

**Pull request closed without merging**
