### PR TITLE
DLM-491/File Size Requesting

### PR DESCRIPTION
**Pull request by MechaRyRy**
## Problem
As detailed in #491, sometimes clients need to process small requests quickly to avoid performance issues where a batch has a lot of small files to process. 

## Solution
As a workaround, until we investigate having parallel head requests for the file sizes we have opted to add an `Optional` `FileSize` to the initial batch builder. If specified then the head requests will be ignored. This is potentially dangerous, if the size is incorrect the batch will fail during the download. We are leaving this to the clients.

## Screen Capture

Before | Screenshot 2019-04-17 at 08 54 20
--- | ---
After | Screenshot 2019-04-17 at 08 54 44

#### On incorrect size specified
when_size_incorrect

### CODE REVIEW

**Comment by MechaRyRy** [comment]
❌ DO NOT MERGE AT THE MOMENT ❌ I need to do some CI work before we merge this.

**Review by frapontillo — DISMISSED** [review]

**Review by zegnus — DISMISSED** [review]

**Comment by ouchadam** [comment]
@Mecharyry is CI work still needed for this? Would be great to have this merged in & released!! 🙏

**Review by ouchadam — DISMISSED** [review]

**Comment by MechaRyRy** [comment]
@ouchadam thanks for reminding me about this! All done now.

**Review by danybony — APPROVED** [review]
💯

**Review by zegnus — APPROVED** [review]

**Pull request merged**
